version: '3.7'
services:
  client:
    restart: always
    build:
      context: ./client
      target: prod
    environment:
      - "SERVER_URL=http://localhost:3007"
      - "NEXT_PUBLIC_SERVER_URL=http://localhost:3007"
    ports:
      - "3000:3000"
  server:
    restart: always
    build:
      context: ./server
      target: prod
    environment:
      - "CLIENT_URL=http://client:3000"
      - "MONGODB_DSN=mongodb://mongo:27017"
    ports:
      - "3007:3007"
    links:
      - client
    depends_on:
      - mongo
  mongo:
    image: "mongo:4.4"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
